<?php
/**
 * @file
 * Install, update and uninstall functions for the Simplify module.
 */

/**
 * Implements hook_uninstall().
 */
function simplify_uninstall() {
  $node_types = node_type_get_names();

  // Delete global variables
  variable_del('simplify_nodes_global');

  // Delete node variables
  foreach ($node_types as $type => $name) {
    variable_del('simplify_nodes_' . $type);
  }
}

// TODO: Add update function to convert variable names from 2.x

